Bug 37868099 - [24558376->25.03.1] Fix Serializer.getName to not throw java.lang.NoClassDefFoundError: javax or jakarta inject.Named when optional inject jar is missing (ce-main->ce-2503) Remote remote.full on coherence-ce/release/coherence-ce-v25.03 success, changes 115838, synced @115839, job.9.20250424095302.12025
[git-p4: depot-paths = "//dev/coherence-ce/release/coherence-ce-v25.03/": change = 115847]