Bug 37868095 - [24558376->14.1.1.0.22] Fix Serializer.getName to not throw java.lang.NoClassDefFoundError: javax or jakarta inject.Named when optional inject jar is missing (14.1.1.0 cl 115848 --> 14.1.1.0 CE)
[git-p4: depot-paths = "//dev/coherence-ce/release/coherence-ce-v14.1.1.0/": change = 115893]