Bug 24558376 - Fix Serializer.getName to not throw java.lang.NoClassDefFoundError: javax or jakarta inject.Named when optional inject jar is missing (14.1.2.0 cl 115835 --> 14.1.2.0 CE)
[git-p4: depot-paths = "//dev/coherence-ce/release/coherence-ce-v14.1.2.0/": change = 115895]