Bug 24558376 - Fix Serializer.getName to not throw java.lang.NoClassDefFoundError: javax or jakarta inject.Named when optional inject jar is missing (auto-submit 115805 after successfully running remote remote.full) Job ID: job.9.20250423200751.8766 (auto-submit integ 115832 main -> coherence-ce/main after successfully running remote remote.full) Job ID: job.9.20250423223501.5806
[git-p4: depot-paths = "//dev/coherence-ce/main/": change = 115834]