Bug 37868098 - [24558376->22.06.13] Fix Serializer.getName to not throw java.lang.NoClassDefFoundError: javax or jakarta inject.Named when optional inject jar is missing (v14.1.1.2206->ce-2206) Remote remote.full on coherence-ce/release/coherence-ce-v22.06 success, changes 115840, synced @115850, job.9.20250424125547.10134
[git-p4: depot-paths = "//dev/coherence-ce/release/coherence-ce-v22.06/": change = 115870]